#!/usr/bin/env bash
#
# A wizard walks you through a manual procedure, step by step.
# Generated by the /wizard skill. Run this in your own terminal: it is
# interactive, reads secrets with hidden input and never prints them.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
#
# Adapted from mattpocock/skills@c55ee46 engineering/wizard (MIT).

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: consistent UX and safe secret transport in every wizard.
# ──────────────────────────────────────────────────────────────────────────

# No terminal, no wizard: hidden prompts and confirmations need a human.
[ -t 0 ] || { printf 'This wizard is interactive: run this in your own terminal.\n' >&2; exit 1; }

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Secrets are read with hidden input\n'
  printf '  and never printed. Stop any time with Ctrl-C and re-run later.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is an action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
# die "..." stops the wizard with a message; nothing after it runs.
die()  { printf '\n  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N]%s ' "$YELLOW" "$1" "$RESET"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret). With no
# current value, empty input is refused as in ask_secret: the prompt repeats,
# and after three empty tries the wizard stops.
ask() {
  local key="$1" prompt="$2" current input="" tries=0
  current=$(_existing "$key" || true)
  while :; do
    if [[ -n "$current" ]]; then
      printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
      printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -r input || true
    [[ -z "$input" && -n "$current" ]] && input="$current"
    [[ -n "$input" ]] && break
    tries=$((tries + 1))
    (( tries < 3 )) || die "no value entered for $key; stopped before changing anything"
    warn "empty input refused; enter the value"
  done
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" reads a secret into $KEY with hidden input. Empty
# input is refused: the prompt repeats, and after three empty tries the
# wizard stops before this stage changes anything.
ask_secret() {
  local key="$1" prompt="$2" input="" tries=0
  while :; do
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    read -rs input || true
    printf '\n'
    [[ -n "$input" ]] && break
    tries=$((tries + 1))
    (( tries < 3 )) || die "no value entered for $key; stopped before changing anything"
    warn "empty input refused; paste the value (it stays hidden)"
  done
  printf -v "$key" '%s' "$input"
}

# ask_optional_secret KEY "Prompt" is ask_secret where Enter skips: $KEY
# stays empty and the caller treats the credential as not needed.
ask_optional_secret() {
  local key="$1" prompt="$2" input=""
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -rs input || true
  printf '\n'
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent. The file ends up readable by you only.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret. The value goes to
# gh on stdin, so it never shows up in the process list. Falls back to a
# warning (and records it) if gh is missing or unauthenticated. Once gh is
# authenticated, a failed set (a 403, the wrong repo) stops the run, and
# gh's own error message stays on screen.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    printf '%s' "$value" | gh secret set "$name" >/dev/null \
      || die "gh could not set GitHub secret $name (see its message above); check your access to this repository"
    WRITTEN_SECRET+=("GitHub:$name")
    printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
    return
  fi
  SKIPPED+=("GitHub secret $name (set it by hand: gh secret set $name, then paste the value)")
  warn "skipped GitHub secret $name: gh is missing or not logged in; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret), also
# through stdin, with the same skip and failure rules as set_secret.
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    printf '%s' "$value" | gh variable set "$name" >/dev/null \
      || die "gh could not set GitHub variable $name (see its message above); check your access to this repository"
    printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
    return
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name: gh is missing or not logged in; set it later"
}

# ── Forgejo ───────────────────────────────────────────────────────────────
# The host, owner and repo come from the git remote (FORGEJO_REMOTE, default
# origin). FORGEJO_URL overrides the web base when the remote uses an SSH
# alias. Credentials live only in shell variables of this run: never
# exported, never written to disk, handed to curl through a config file on a
# process substitution so they never appear in its argv.

# _cfg_escape VALUE escapes a value for a double-quoted curl config field.
_cfg_escape() { local s="${1//\\/\\\\}"; s="${s//\"/\\\"}"; printf '%s' "$s"; }

# forgejo_remote sets FORGEJO_HOST/OWNER/REPO/WEB/API from the git remote.
forgejo_remote() {
  local remote="${FORGEJO_REMOTE:-origin}" url rest hostpart scheme="https"
  url=$(git remote get-url "$remote" 2>/dev/null) || die "no git remote '$remote' here; run the wizard from the repository"
  case "$url" in
    http://*|https://*)
      scheme="${url%%://*}"; rest="${url#*://}"
      hostpart="${rest%%/*}"; hostpart="${hostpart##*@}"; rest="${rest#*/}" ;;
    ssh://*)
      rest="${url#ssh://}"
      hostpart="${rest%%/*}"; hostpart="${hostpart##*@}"; hostpart="${hostpart%%:*}"; rest="${rest#*/}" ;;
    *:*)
      rest="${url#*@}"; hostpart="${rest%%:*}"; rest="${rest#*:}" ;;
    *) die "cannot read a host from git remote '$remote'" ;;
  esac
  rest="${rest%/}"; rest="${rest%.git}"
  FORGEJO_HOST="$hostpart"; FORGEJO_OWNER="${rest%%/*}"; FORGEJO_REPO="${rest#*/}"
  [[ -n "$FORGEJO_HOST" && -n "$FORGEJO_OWNER" && -n "$FORGEJO_REPO" && "$FORGEJO_REPO" != */* ]] \
    || die "cannot read owner/repo from git remote '$remote'"
  FORGEJO_WEB="${FORGEJO_URL:-${scheme}://${FORGEJO_HOST}}"; FORGEJO_WEB="${FORGEJO_WEB%/}"
  FORGEJO_API="${FORGEJO_WEB}/api/v1"
  say "Forgejo instance: ${FORGEJO_WEB}   repository: ${FORGEJO_OWNER}/${FORGEJO_REPO}"
  confirm "Is this the right instance and repository?" \
    || die "set FORGEJO_URL (web base) or FORGEJO_REMOTE (remote name) and re-run"
}

# forgejo_login asks for the optional reverse-proxy Basic-auth credential
# first (Enter skips it), then for the Forgejo token.
forgejo_login() {
  [[ -n "${FORGEJO_API:-}" ]] || forgejo_remote
  command -v curl >/dev/null 2>&1 || die "curl is required for the Forgejo stage"
  command -v jq   >/dev/null 2>&1 || die "jq is required for the Forgejo stage"
  say "Optional: if ${FORGEJO_HOST} sits behind a reverse proxy with its own login, enter that credential."
  ask_optional_secret _FJ_PROXY "Reverse-proxy auth as user:password (Enter skips):"
  open_url "${FORGEJO_WEB}/user/settings/applications"
  step "Generate a token with write access to repository, then copy it."
  ask_secret _FJ_PAT "Paste the Forgejo token:"
}

# _forgejo_send METHOD PATH sends the JSON body it reads on stdin to the repo
# API path and prints the HTTP status (000 when curl itself fails). Call
# forgejo_login first: this runs inside a pipeline, so it cannot prompt.
_forgejo_send() {
  local method="$1" path="$2" code="" user_line="" pat
  pat=$(_cfg_escape "$_FJ_PAT")
  [[ -n "${_FJ_PROXY:-}" ]] && user_line="user = \"$(_cfg_escape "$_FJ_PROXY")\""
  code=$(curl -K <(printf '%s\nheader = "Authorization: token %s"\n' "$user_line" "$pat") \
      -sS -o /dev/null -w '%{http_code}' -X "$method" \
      -H 'Content-Type: application/json' --data-binary @- \
      "${FORGEJO_API}/repos/${FORGEJO_OWNER}/${FORGEJO_REPO}/${path}") \
    || code="${code:-000}"
  printf '%s' "${code:-000}"
}

# set_forgejo_secret NAME VALUE creates or updates a Forgejo Actions repo
# secret. The secret travels on stdin all the way: printf (a builtin) feeds
# jq, which builds the JSON body, and curl sends it; it is never an argument
# of any command. Only HTTP 201 (created) or 204 (updated) counts as
# success, anything else stops the run.
set_forgejo_secret() {
  local name="$1" value="$2" code=""
  [[ -n "${_FJ_PAT:-}" ]] || forgejo_login
  code=$(printf '%s' "$value" | jq -Rs '{data: .}' | _forgejo_send PUT "actions/secrets/${name}") \
    || code="${code:-000}"
  case "$code" in
    201|204)
      WRITTEN_SECRET+=("Forgejo:$name")
      printf '  %s✓ set%s Forgejo secret %s (HTTP %s)\n' "$GREEN" "$RESET" "$name" "$code" ;;
    *)
      die "Forgejo refused secret $name (HTTP $code). 401/403: check the token scope and the reverse-proxy credential; 404: check owner/repo and that Actions is enabled." ;;
  esac
}

# set_forgejo_var NAME VALUE creates or updates a Forgejo Actions repo
# variable. The value is public, so jq may take it as an argument; never use
# this for a secret. It updates first and creates on 404; only 201 or 204
# counts as success.
set_forgejo_var() {
  local name="$1" value="$2" code=""
  [[ -n "${_FJ_PAT:-}" ]] || forgejo_login
  code=$(jq -n --arg value "$value" '{value: $value}' | _forgejo_send PUT "actions/variables/${name}") \
    || code="${code:-000}"
  if [[ "$code" == 404 ]]; then
    code=$(jq -n --arg value "$value" '{value: $value}' | _forgejo_send POST "actions/variables/${name}") \
      || code="${code:-000}"
  fi
  case "$code" in
    201|204)
      printf '  %s✓ set%s Forgejo variable %s (HTTP %s)\n' "$GREEN" "$RESET" "$name" "$code" ;;
    *)
      die "Forgejo refused variable $name (HTTP $code). 401/403: check the token scope and the reverse-proxy credential; 404: check owner/repo and that Actions is enabled." ;;
  esac
}

# finish clears, then shows a closing summary and drops held credentials.
finish() {
  _clear
  printf '\n%s%s  ✓ Done%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  unset _FJ_PAT _FJ_PROXY
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=2

banner "Example: rotate the CI deploy token"

# ── Example stages: replace with your real steps ─────────────────────────
stage "Deploy token: new value"
say "We'll create a fresh deploy token and store it as the CI secret DEPLOY_TOKEN."
step "In the provider's dashboard, create a new deploy token and copy it."
ask_secret DEPLOY_TOKEN "Paste the new deploy token:"
confirm "Replace the CI secret DEPLOY_TOKEN now? CI uses the new value from the next run." \
  || die "stopped before any change"

stage "Deploy token: CI secret"
# Forgejo remote: keep this line. GitHub remote: use set_secret instead.
set_forgejo_secret DEPLOY_TOKEN "$DEPLOY_TOKEN"
# set_secret DEPLOY_TOKEN "$DEPLOY_TOKEN"
step "Revoke the old token in the provider's dashboard once CI is green."
pause "Press Enter when the old token is revoked."
# ──────────────────────────────────────────────────────────────────────────

finish
